# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c9d2096add716a095a026117f2bfb41a431f2c09ccf0c4d43d0f44a3dec2cfc9d386148ce864c121e7347b8278e9cd821e57bdc0b28af974d6296e3c48b837b7

test:
  secret_key_base: 83d47cfe8562f8c849f6b6dd014d673531eab5b6951f5f08a61bf10e94d4a3b31476138de005177392b87cfdfe81fcf425a16a112c40aeef17480a77ab2f2f43

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
